# Konfigurationsdatei für das Release-Drafter-Tool.
# release-drafter-config.yml

# Definiert die Vorlage für den Namen des Releases.
name-template: 'v$RESOLVED_VERSION' # Automatisch erhöhte Versionsnummer

# Definiert die Vorlage für den Namen des Release-Tags.
tag-template: 'v$RESOLVED_VERSION' # Automatisch erhöhte Versionsnummer

# Definiert die Kategorien, die im Changelog angezeigt werden. Jede Kategorie kann
# durch ein oder mehrere Labels identifiziert werden. Pull Requests, die diese Labels verwenden,
# werden automatisch unter der entsprechenden Kategorie im Changelog aufgeführt.
categories:
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Dokumentation'
    labels:
      - 'documentation'

# Definiert das allgemeine Layout des Changelogs.
# $CHANGES wird durch die Liste der Änderungen ersetzt, die gemäß `change-template` formatiert sind.
template: |
  ## Änderungen
  $CHANGES

# Definiert die Kategorien, die im Changelog angezeigt werden. Jede Kategorie kann
# durch ein oder mehrere Labels identifiziert werden. Pull Requests, die diese Labels verwenden,
# werden automatisch unter der entsprechenden Kategorie im Changelog aufgeführt.
# Standardmäßig wird die Patch-Version erhöht. Für Minor-Updates wird ein entsprechendes Label benötigt.
# Major-Updates werden manuell verwaltet und sind nicht automatisiert.
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'documentation'
  default: minor