# Konfigurationsdatei für das Release-Drafter-Tool.
# release-drafter-config.yml

name-template: 'v${{ env.NEXT_VERSION }}' # Name des Releases wird aus der Umgebungsvariable NEXT_VERSION abgeleitet.
tag-template: 'v${{ env.NEXT_VERSION }}' # Tag des Releases wird aus der Umgebungsvariable NEXT_VERSION abgeleitet.


# Definiert die Kategorien, die im Changelog angezeigt werden. Jede Kategorie kann
# durch ein oder mehrere Labels identifiziert werden. Pull Requests, die diese Labels verwenden,
# werden automatisch unter der entsprechenden Kategorie im Changelog aufgeführt.
categories:
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Dokumentation'
    labels:
      - 'documentation'

# Definiert das Format einer einzelnen Änderung im Changelog.
# $TITLE wird durch den Titel des Pull Requests oder Commit-Titels ersetzt,
# $AUTHOR durch den GitHub-Nutzernamen des Autors und $NUMBER durch die Pull Request Nummer.
# Diese Formatierung wird für jede im Changelog gelistete Änderung verwendet.
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

# Definiert das allgemeine Layout des Changelogs.
# $CHANGES wird durch die Liste der Änderungen ersetzt, die gemäß `change-template` formatiert sind.
template: |
  ## Änderungen
  $CHANGES

