# bump-csproj-version.yml

name: Bump csproj Version

on:
  workflow_call:
    inputs:
      csprojPath:
        type: string
        description: 'Path to the csproj file to update'
        required: true
      versionType:
        type: string
        description: 'Type of version increment: major, minor, patch, preview'
        default: minor

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: "${{ inputs.csprojPath }}"
          version: bump-build

      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Bump project version to ${{ steps.bump.outputs.newVersion }}"
          git push
