name: Draft Release
on:
  push:

env:
  VERSION_INCREMENT: 'minor'  # Alternativ: major, patch
  LATEST_VERSION: ''         # Wird im Job 'read_release_data' gesetzt
  NEXT_VERSION: ''           # Wird im Job 'calculate_next_version' gesetzt

jobs:
  read_release_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Get latest release
        id: get_release
        run: |
          RELEASE_JSON=$(gh release view --json tagName,name,url)
          RELEASE_TAG_NAME=$(echo "$RELEASE_JSON" | jq -r '.tagName')
          RELEASE_NAME=$(echo "$RELEASE_JSON" | jq -r '.name')
          RELEASE_URL=$(echo "$RELEASE_JSON" | jq -r '.url')
          LATEST_VERSION="${RELEASE_TAG_NAME#"v"}" # Remove leading 'v'
          echo "release_version=$LATEST_VERSION"
          echo "release_tag_name=$RELEASE_TAG_NAME"
          echo "release_url=$RELEASE_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  calculate_next_version:
    needs: read_release_data
    runs-on: ubuntu-latest
    steps:
      - name: Calculate next version
        run: |
          IFS='.' read -ra VERSION_PARTS <<< "$LATEST_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          if [[ "$VERSION_INCREMENT" == "major" ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ "$VERSION_INCREMENT" == "minor" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [[ "$VERSION_INCREMENT" == "patch" ]]; then
            PATCH=$((PATCH + 1))
          fi
          NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Print next version
        run: |
          echo "Next Version: $NEXT_VERSION"

  draft_release:
    needs: calculate_next_version
    runs-on: ubuntu-latest
    steps:
      - name: Print next version for verification
        run: |
          echo "Next Version: $NEXT_VERSION"

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter-config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: ${{ env.NEXT_VERSION }}
