name: Draft Release
on:
  push:

env:
  VERSION_INCREMENT: 'minor'  # Alternativ: major, patch

jobs:
  read_release_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release
        id: get_release
        run: |
          RELEASE_JSON=$(gh release view --json tagName,name,url)
          RELEASE_TAG_NAME=$(echo "$RELEASE_JSON" | jq -r '.tagName')
          RELEASE_NAME=$(echo "$RELEASE_JSON" | jq -r '.name')
          RELEASE_URL=$(echo "$RELEASE_JSON" | jq -r '.url')
          RELEASE_VERSION="${RELEASE_TAG_NAME#"v"}"
          echo "release_version=$RELEASE_VERSION" >> "$GITHUB_ENV"
          echo "release_tag_name=$RELEASE_TAG_NAME" >> "$GITHUB_ENV"
          echo "release_url=$RELEASE_URL" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

  calculate_next_version:
    needs: read_release_data
    runs-on: ubuntu-latest
    steps:
      - name: Calculate next version
        run: |
          LATEST_VERSION=${{ needs.read_release_data.outputs.release_version }}
          IFS='.' read -ra VERSION_PARTS <<< "$LATEST_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          VERSION_INCREMENT=$VERSION_INCREMENT
          if [[ "$VERSION_INCREMENT" == "major" ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ "$VERSION_INCREMENT" == "minor" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [[ "$VERSION_INCREMENT" == "patch" ]]; then
            PATCH=$((PATCH + 1))
          fi
          NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
    
      - name: Print next version
        env:
          NEXT_VERSION: ${{ env.NEXT_VERSION }}
        run: |
          echo "Next Version: $NEXT_VERSION"

  draft_release:
    needs: calculate_next_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print next version
        env:
          NEXT_VERSION: ${{ env.NEXT_VERSION }}
        run: |
          echo "Next Version: $NEXT_VERSION"

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter-config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: ${{ env.NEXT_VERSION }}
