name: Draft Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    env:
      VERSION: '' # Wird im nächsten Schritt gesetzt
    steps:
      - name: Run Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter-config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove leading 'v' from tag name and store in release_version
        run: |
          TAG_NAME="${{ steps.release_drafter.outputs.tag_name }}"
          echo "Tag name: $TAG_NAME"
          VERSION="${TAG_NAME#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

    outputs:
      release_id: ${{ steps.release_drafter.outputs.id }}
      release_name: ${{ steps.release_drafter.outputs.name }}
      release_tag_name: ${{ steps.release_drafter.outputs.tag_name }}
      release_body: ${{ steps.release_drafter.outputs.body }}
      release_html_url: ${{ steps.release_drafter.outputs.html_url }}
      release_upload_url: ${{ steps.release_drafter.outputs.upload_url }}
      release_version: ${{ env.VERSION }}
