name: Echo Message Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
        description: 'The message to echo'

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the input message
        run: echo "${{ inputs.message }}"
