# Dies ist ein Beispiel für die Verwendung von Workflows in GitHub.

name: Use Echo Message Workflow

on:
  push:
    branches:
      - main

jobs:
  call-echo-workflow:
    uses: kurmann/GitHub.Workflows/.github/workflows/echo_message.yml@main
