name: 'Get Latest Release or Prerelease Information'

on:
  workflow_call:
    outputs:
      release_version:
        description: "The latest release version"
        value: ${{ jobs.get_info.outputs.release_version }}
      release_tag_name:
        description: "The latest release tag name"
        value: ${{ jobs.get_info.outputs.release_tag_name }}
      release_url:
        description: "URL of the latest release"
        value: ${{ jobs.get_info.outputs.release_url }}
      release_is_prerelease:
        description: "Indicates if it is a prerelease"
        value: ${{ jobs.get_info.outputs.release_is_prerelease }}

jobs:
  get_info:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_info.outputs.release_version }}
      release_tag_name: ${{ steps.get_info.outputs.release_tag_name }}
      release_url: ${{ steps.get_info.outputs.release_url }}
      release_is_prerelease: ${{ steps.get_info.outputs.release_is_prerelease }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release or prerelease
        id: get_info
        run: |
          RELEASES_JSON=$(gh release list --json tagName,name,isPrerelease --exclude-drafts)
          LATEST_RELEASE_OR_PRERELEASE_JSON=$(echo "$RELEASES_JSON" | jq -r '.[0]')
          
          RELEASE_TAG_NAME=$(echo "$LATEST_RELEASE_OR_PRERELEASE_JSON" | jq -r '.tagName')
          RELEASE_NAME=$(echo "$LATEST_RELEASE_OR_PRERELEASE_JSON" | jq -r '.name')
          RELEASE_IS_PRERELEASE=$(echo "$LATEST_RELEASE_OR_PRERELEASE_JSON" | jq -r '.isPrerelease')
          RELEASE_VERSION="${RELEASE_TAG_NAME#"v"}"
          
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          RELEASE_URL="${REPO_URL}/releases/tag/${RELEASE_TAG_NAME}"
          
          echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
          echo "release_tag_name=$RELEASE_TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "release_url=$RELEASE_URL" >> "$GITHUB_OUTPUT"
          echo "release_is_prerelease=$RELEASE_IS_PRERELEASE" >> "$GITHUB_OUTPUT"

          echo "Found latest $(if [ "$RELEASE_IS_PRERELEASE" = "true" ]; then echo "prerelease"; else echo "release"; fi): $RELEASE_TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
