# .github/workflows/get_current_release.yml
name: Print Current Release

on:
  push:

jobs:
  get_release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest release
      id: get_release
      run: |
        RELEASE_JSON=$(gh release view --json tagName,name,body)
        RELEASE_TAG_NAME=$(echo "$RELEASE_JSON" | jq -r '.tagName')
        RELEASE_NAME=$(echo "$RELEASE_JSON" | jq -r '.name')
        RELEASE_BODY=$(echo "$RELEASE_JSON" | jq -r '.body' | jq -sRr @json)
        RELEASE_VERSION="${RELEASE_NAME#"v"}"  # Entfernt das 'v' am Anfang, falls vorhanden
        echo "RELEASE_TAG_NAME=$RELEASE_TAG_NAME" >> $GITHUB_ENV
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
        echo "RELEASE_BODY=$RELEASE_BODY" >> $GITHUB_ENV
        echo "LATEST_RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
        echo "Using version $RELEASE_VERSION for package."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print release information
      run: |
        echo "Release name (version): $RELEASE_NAME"
        echo "Release body: $RELEASE_BODY"