# .github/workflows/get_current_release.yml
name: Print Current Release

on:
  push:

jobs:
  get_release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest release
      id: latest_release
      uses: kaliber5/action-get-release@v1
      with:
        token: ${{ github.token }}
        latest: true

    - name: Print release information
      run: |
        echo "Release version: ${{ steps.latest_release.outputs.version }}"
        echo "Release title: ${{ steps.latest_release.outputs.name }}"
        echo "Release body: ${{ steps.latest_release.outputs.body }}"