name: Get Latest Release Info

on:
  workflow_dispatch:

jobs:
  read_and_print_release_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release
        id: get_release
        run: |
          RELEASE_JSON=$(gh release view --json tagName,name,body,url)
          RELEASE_TAG_NAME=$(echo "$RELEASE_JSON" | jq -r '.tagName')
          RELEASE_NAME=$(echo "$RELEASE_JSON" | jq -r '.name')
          RELEASE_URL=$(echo "$RELEASE_JSON" | jq -r '.url')
          RELEASE_BODY=$(echo "$RELEASE_JSON" | jq -r '.body' | jq -sRr @json)
          RELEASE_VERSION="${RELEASE_TAG_NAME#"v"}"
          echo "::set-output name=release_version::$RELEASE_VERSION"
          echo "::set-output name=release_tag_name::$RELEASE_TAG_NAME"
          echo "::set-output name=release_body::$RELEASE_BODY"
          echo "::set-output name=release_url::$RELEASE_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release_version: ${{ steps.get_release.outputs.release_version }}
      release_tag_name: ${{ steps.get_release.outputs.release_tag_name }}
      release_body: ${{ steps.get_release.outputs.release_body }}
      release_url: ${{ steps.get_release.outputs.release_url }}

  second_job:
    needs: read_and_print_release_data
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        run: |
          echo "Release Version: ${{ needs.read_and_print_release_data.outputs.release_version }}"
          echo "Release Tag Name: ${{ needs.read_and_print_release_data.outputs.release_tag_name }}"
          echo "Release Body: ${{ needs.read_and_print_release_data.outputs.release_body }}"
          echo "Release URL: ${{ needs.read_and_print_release_data.outputs.release_url }}"