# .github/workflows/release-drafter.yml im zentralen Repository
name: 'Release Drafter'

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter-config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
