name: Create Release Draft

on:
  push:
    branches:
      - main  # Führt diesen Workflow aus, wenn Änderungen an den main Branch gepusht werden

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # Definiert den Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Holt die gesamte Git-Historie für GitVersion

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9
      with:
        useConfigFile: true
        configFilePath: 'GitVersion.yml'

    - name: Create GitHub Release Draft
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nutzt das GitHub Token für Authentifizierung
      with:
        tag_name: ${{ steps.gitversion.outputs.semVer }}  # Setzt den Tag-Namen zur Version
        release_name: Release ${{ steps.gitversion.outputs.semVer }}
        draft: true
        body: |
          Changes in this Release:
          - ${{ steps.gitversion.outputs.commitsSinceVersionSource }} commits since last version.
          ### Features
          * New features added
          ### Fixes
          * Bugs fixed

    - name: Tag Repository
      run: |
        git tag ${{ steps.gitversion.outputs.semVer }}
        git push origin ${{ steps.gitversion.outputs.semVer }}
