# .github/workflows/release-drafter.yml im zentralen Repository
name: 'Release Drafter'

on:
  workflow_call:
    secrets:
      github_token:
        required: true

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter-config.yml'  # Pfad zur zentralen Konfigurationsdatei
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
