name: Create Release Draft

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Holt die gesamte Git-Historie für GitVersion

    - name: Install and Use GitVersion
      uses: GitTools/actions/gitversion/execute@v1.1.1
      with:
        configFilePath: 'GitVersion.yml'

    - name: Create GitHub Release Draft
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.semver }}  # Diese Variable könnte je nach Ausgabe von GitVersion variieren
        release_name: Release ${{ steps.gitversion.outputs.semver }}
        draft: true
        body: |
          Changes in this Release:
          - Some changes description.
          ### Features
          * New features added
          ### Fixes
          * Bugs fixed

    - name: Tag Repository
      run: |
        git tag ${{ steps.gitversion.outputs.semver }}
        git push origin ${{ steps.gitversion.outputs.semver }}
