name: Test Get Latest Release Info
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/get_latest_release_info.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release_version: ${{ steps.get_latest_release_info.outputs.release_version }}
      release_tag_name: ${{ steps.get_latest_release_info.outputs.release_tag_name }}
      release_url: ${{ steps.get_latest_release_info.outputs.release_url }}

  another_job:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        run: |
          echo "Release version: ${{ needs.test.outputs.release_version }}"
          echo "Release tag name: ${{ needs.test.outputs.release_tag_name }}"
          echo "Release URL: ${{ needs.test.outputs.release_url }}"